[package]
name = "enclave-runtime"
version = "0.1.0"
edition = "2021"

[dependencies]
sgx_types = { git = "https://github.com/apache/teaclave-sgx-sdk.git" }
sgx_tstd = { git = "https://github.com/apache/teaclave-sgx-sdk.git", features = ["net"] }
sgx_trts = { git = "https://github.com/apache/teaclave-sgx-sdk.git" }
sgx_tse = { git = "https://github.com/apache/teaclave-sgx-sdk.git" }
sgx_tcrypto = { git = "https://github.com/apache/teaclave-sgx-sdk.git" }
serde = { version = "1.0", default-features = false, features = ["alloc"] }
serde_json = { version = "1.0", default-features = false, features = ["alloc"] }
base64 = { rev = "dc7389e10817b078f289386b3b6a852ab6c4c021", git = "https://github.com/mesalock-linux/rust-base64-sgx" }
itertools = { version = "0.8", default-features = false, features = [] }
env_logger = { git = "https://github.com/mesalock-linux/env_logger-sgx", default-features = false, features = ["mesalock_sgx"] }
log = { git = "https://github.com/mesalock-linux/log-sgx" }
ctor = "0.1.13"
lazy_static = { version = "1.1.0", features = ["spin_no_std"] }
anyhow = { rev = "sgx_1.1.3", git = "https://github.com/mesalock-linux/anyhow-sgx.git" }
thiserror = { git = "https://github.com/mesalock-linux/thiserror-sgx.git" }
ibc = { git = "https://github.com/informalsystems/ibc-rs", rev = "e8c98d440949abf971ac45a68ed9dd9e6e9f48ed", default-features = false }
prost-types = { version = "0.10", default-features = false }
bincode = { git = "https://github.com/bluele/bincode-sgx", branch = "serde" }
derive_more = { version = "0.99.17", default-features = false, features = ["from", "display"] }

enclave-utils = { path = "../utils" }

handler = { path = "../../modules/handler", default-features = false, features = ["sgx"] }
light-client = { path = "../../modules/light-client", default-features = false, features = ["sgx"] }
tendermint-lc = { path = "../../modules/tendermint-lc", default-features = false, features = ["sgx"] }
enclave-commands = { path = "../../modules/enclave-commands", default-features = false, features = ["sgx"] }
store = { path = "../../modules/store", default-features = false, features = ["sgx"] }
settings = { path = "../../modules/settings", default-features = false, features = ["sgx"] }
crypto = { path = "../../modules/crypto", default-features = false, features = ["sgx"] }

corda-ibc-enclave-light-client = { git = "https://github.com/datachainlab/corda-ibc-rs.git", default-features = false, features = ["sgx"] }
