[package]
name = "store"
version = "0.1.0"
edition = "2021"

[dependencies]
sgx_tstd = { git = "https://github.com/apache/teaclave-sgx-sdk.git", optional = true }
serde = { version = "1.0", default-features = false, features = ["alloc", "derive"] }
serde_json = { version = "1.0", default-features = false, features = ["alloc"] }
sha2 = { version = "0.8", default-features = false }
derive_more = { version = "0.99.17", default-features = false, features = ["from", "display"] }
crypto = { git = "https://github.com/datachainlab/lcp.git", default-features = false }

log-sgx = { package = "log", git = "https://github.com/mesalock-linux/log-sgx", optional = true }
log = { version = "0.4.8", optional = true }
anyhow-sgx = { package = "anyhow", rev = "sgx_1.1.3", git = "https://github.com/mesalock-linux/anyhow-sgx.git", optional = true }
anyhow = { version = "1.0.56", optional = true }
bincode-sgx = { package = "bincode", git = "https://github.com/bluele/bincode-sgx", branch = "serde", optional = true }
bincode = { version = "1.3", optional = true }
thiserror-sgx = { package = "thiserror", git = "https://github.com/mesalock-linux/thiserror-sgx.git", optional = true }
thiserror = { version = "1.0.30", optional = true }

[features]
default = ["std"]
std = [
    "anyhow",
    "bincode",
    "thiserror",
    "log",
    "crypto/std"
]
sgx = [
    "sgx_tstd",
    "anyhow-sgx",
    "bincode-sgx",
    "thiserror-sgx",
    "log-sgx",
    "crypto/sgx"
]
