[package]
name = "enclave-remote-attestation"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sgx_types = { git = "https://github.com/apache/teaclave-sgx-sdk.git" }
sgx_tstd = { git = "https://github.com/apache/teaclave-sgx-sdk.git", features = ["net"] }
sgx_trts = { git = "https://github.com/apache/teaclave-sgx-sdk.git" }
sgx_tse = { git = "https://github.com/apache/teaclave-sgx-sdk.git" }
sgx_tcrypto = { git = "https://github.com/apache/teaclave-sgx-sdk.git" }

serde = { version = "1.0", default-features = false, features = ["alloc"] }
serde_json = { version = "1.0", default-features = false, features = ["alloc"] }
itertools = { version = "0.8", default-features = false, features = [] }
log = { git = "https://github.com/mesalock-linux/log-sgx" }
webpki = { git = "https://github.com/mesalock-linux/webpki", branch = "mesalock_sgx" }
webpki-roots = { git = "https://github.com/mesalock-linux/webpki-roots", rev = "6ff3be547ac13ccd46ae55605ad6506ce30688ef" }
rustls = { git = "https://github.com/mesalock-linux/rustls", branch = "mesalock_sgx" }
base64 = { rev = "dc7389e10817b078f289386b3b6a852ab6c4c021", git = "https://github.com/mesalock-linux/rust-base64-sgx" }
hex = { version = "0.4", default-features = false, features = ["alloc"] }
httparse = { version = "1.3", default-features = false }
chrono = { version = "0.4.19", default-features = false, features = ["alloc"]}

crypto = { git = "https://github.com/datachainlab/lcp.git", default-features = false, features = ["sgx"] }
attestation-report = { git = "https://github.com/datachainlab/lcp.git", default-features = false, features = ["sgx"] }
settings = { git = "https://github.com/datachainlab/lcp.git", default-features = false, features = ["sgx"]  }
