[package]
name = "service"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.8"
ibc = { git = "https://github.com/informalsystems/ibc-rs", rev = "e8c98d440949abf971ac45a68ed9dd9e6e9f48ed", default-features = false }
ibc-proto = { git = "https://github.com/informalsystems/ibc-rs", rev = "e8c98d440949abf971ac45a68ed9dd9e6e9f48ed", default-features = false, features = ["server"] }
tonic = { version = "0.7", default-features = false }
tokio = { version = "1.0", features = ["full"] }
anyhow = { version = "1.0.56" }

enclave-api = { git = "https://github.com/datachainlab/lcp.git" }
